[package]
name = "website"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
handlebars.features = ["dir_source"]
handlebars.version = "6.2.0"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
serde_yml = "0.0.12"

[workspace]
members = ["serve"]
