[package]
name = "serve"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
tokio = { version = "1.40", features = ["full"] }
warp = "0.3"
website = { version = "0.1.0", path = ".." }

